spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authority_management?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    timeout: 3000

  elasticsearch:
    rest:
      uris:
        - http://10.211.55.4:9200
        - http://10.211.55.5:9200


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.goku.authority.dao.po